{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "878a94e2_994e59a0",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 13
      },
      "lineNbr": 0,
      "author": {
        "id": 34352
      },
      "writtenOn": "2024-02-28T06:17:11Z",
      "side": 1,
      "message": "This succeeds for me locally:\n\n```\n...\n2024-02-28 16:44:48 [INFO] ## Running Test zaza.sunbeam.charm_tests.tempest_k8s.tests.TempestK8sTest ##\n2024-02-28 16:44:48 [INFO] test_get_lists (zaza.sunbeam.charm_tests.tempest_k8s.tests.TempestK8sTest.test_get_lists)\n2024-02-28 16:44:48 [INFO] Verify that the get-lists action returns list names as expected.\n2024-02-28 16:44:48 [INFO]  ...\n2024-02-28 16:44:49 [INFO] ok\n2024-02-28 16:44:49 [INFO] test_validate_with_readonly_quick_tests (zaza.sunbeam.charm_tests.tempest_k8s.tests.TempestK8sTest.test_validate_with_readonly_quick_tests)\n2024-02-28 16:44:49 [INFO] Verify that the validate action runs tests as expected.\n2024-02-28 16:44:49 [INFO]  ...\n2024-02-28 16:45:08 [INFO] ok\n2024-02-28 16:45:08 [INFO] test_validate_with_readonly_quick_tests_regex (zaza.sunbeam.charm_tests.tempest_k8s.tests.TempestK8sTest.test_validate_with_readonly_quick_tests_regex)\n2024-02-28 16:45:08 [INFO] Verify that the validate action runs tests with filter.\n2024-02-28 16:45:08 [INFO]  ...\n2024-02-28 16:45:24 [INFO] action.data \u003d {\u0027model-uuid\u0027: \u0027ebe51f9c-4c61-4462-8bb5-bb9ea2f701e8\u0027, \u0027id\u0027: \u002720\u0027, \u0027receiver\u0027: \u0027tempest/0\u0027, \u0027name\u0027: \u0027validate\u0027, \u0027status\u0027: \u0027completed\u0027, \u0027message\u0027: \u0027\u0027, \u0027enqueued\u0027: \u00272024-02-28T06:15:09Z\u0027, \u0027started\u0027: \u00272024-02-28T06:15:09Z\u0027, \u0027completed\u0027: \u00272024-02-28T06:15:24Z\u0027, \u0027results\u0027: {\u0027info\u0027: \u0027For detailed results, copy the log file from the container by running:\\n$ juju scp -m zaza-3199694d776a --container tempest tempest/0:/var/lib/tempest/workspace/tempest-validation.log validation.log\u0027, \u0027return-code\u0027: 0, \u0027summary\u0027: \u0027Totals\\n\u003d\u003d\u003d\u003d\u003d\u003d\\nRan: 2 tests in 0.0139 sec.\\n - Passed: 1\\n - Skipped: 1\\n - Expected Fail: 0\\n - Unexpected Success: 0\\n - Failed: 0\\nSum of execute time for each test: 0.0090 sec.\\n\u0027}}\n2024-02-28 16:45:24 [INFO] ok\n2024-02-28 16:45:24 [INFO] ----------------------------------------------------------------------\n2024-02-28 16:45:24 [INFO] Ran 3 tests in 36.929s\n2024-02-28 16:45:24 [INFO] OK\n2024-02-28 16:45:24 [INFO] Finished testing zaza-3199694d776a\n\n...\n\n  func: OK (829.08\u003dsetup[70.76]+cmd[0.08,758.24] seconds)\n  congratulations :) (829.15 seconds)\n\n```",
      "revId": "59977fd29fc1f700f37ce61a2e34d1bb42aa84d1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e61607e6_821d1d19",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 13
      },
      "lineNbr": 0,
      "author": {
        "id": 34352
      },
      "writtenOn": "2024-02-29T00:35:49Z",
      "side": 1,
      "message": "recheck\n\nThe validate action tests are super flaky, but I\u0027m not sure where it\u0027s coming from.  The logs seem to suggest connection errors everywhere, but I\u0027m not sure why: https://storage.bhs.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_861/909632/13/check/func-test-core/861ca16/job-output.txt",
      "revId": "59977fd29fc1f700f37ce61a2e34d1bb42aa84d1",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}