{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b4f62f04_01c20bba",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 10366
      },
      "writtenOn": "2025-05-05T01:03:51Z",
      "side": 1,
      "message": "recheck issue with setuptools https://github.com/pypa/setuptools/issues/4976 fixed and released",
      "revId": "61aed1308426e658836d43bb5d744bf0577c4739",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}