{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "b3be0590_b503187b",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 9426
      },
      "writtenOn": "2025-06-17T10:12:04Z",
      "side": 1,
      "message": "recheck",
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "77b16180_1a00df45",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 35761
      },
      "writtenOn": "2025-06-18T12:08:12Z",
      "side": 1,
      "message": "This overall looks good",
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "e4b5defe_f9ca5b4a",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 8
      },
      "lineNbr": 0,
      "author": {
        "id": 35761
      },
      "writtenOn": "2025-06-18T12:38:37Z",
      "side": 1,
      "message": "Resetting vote while I debug a local deployment",
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "de33d712_b0d4f24a",
        "filename": "charms/keystone-k8s/src/charm.py",
        "patchSetId": 8
      },
      "lineNbr": 390,
      "author": {
        "id": 35761
      },
      "writtenOn": "2025-06-19T12:44:35Z",
      "side": 1,
      "message": "After tripping on this, I feel like this section should raise a `sunbeam_guard.BlockedException` stating that we can\u0027t validate the issuer url got from the relation.\n\nCurrent behaviour is just a log message and we don\u0027t want the user to feel like everything is going good while that\u0027s not the case.",
      "range": {
        "startLine": 390,
        "startChar": 12,
        "endLine": 390,
        "endChar": 18
      },
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "0b4dd65b_831a8145",
        "filename": "charms/keystone-k8s/src/charm.py",
        "patchSetId": 8
      },
      "lineNbr": 390,
      "author": {
        "id": 9426
      },
      "writtenOn": "2025-06-19T13:11:56Z",
      "side": 1,
      "message": "That is a great idea. Will push an update soon.",
      "parentUuid": "de33d712_b0d4f24a",
      "range": {
        "startLine": 390,
        "startChar": 12,
        "endLine": 390,
        "endChar": 18
      },
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "749c2009_b0c6b0dd",
        "filename": "charms/keystone-k8s/src/charm.py",
        "patchSetId": 8
      },
      "lineNbr": 2058,
      "author": {
        "id": 35761
      },
      "writtenOn": "2025-06-18T12:08:12Z",
      "side": 1,
      "message": "nitpicking:\n\nIs there a reason sync_oidc_providers is run before init_container_services? \n\ninit_container_services will bailout the charm if any container is missing / unready. While that\u0027s not an issue here as the run_db_sync will also bailout as there\u0027s only 1 workload container, let\u0027s keep the semantics",
      "range": {
        "startLine": 2058,
        "startChar": 13,
        "endLine": 2058,
        "endChar": 32
      },
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "bbb1cdd0_21e901bd",
        "filename": "charms/keystone-k8s/src/charm.py",
        "patchSetId": 8
      },
      "lineNbr": 2058,
      "author": {
        "id": 9426
      },
      "writtenOn": "2025-06-18T13:34:23Z",
      "side": 1,
      "message": "Yes. Apache will fail to start and the charm will enter an error state if the wsgi conf is generated with the oidc settings, but the oidc metadata dir doesn\u0027t yet exist.\n\nThis can happen if the workload container is recreated for whatever reason.",
      "parentUuid": "749c2009_b0c6b0dd",
      "range": {
        "startLine": 2058,
        "startChar": 13,
        "endLine": 2058,
        "endChar": 32
      },
      "revId": "ded387a0027c2dfbee3ca7fa10e5514fbda4013c",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}